language: java
sudo: required
dist: trusty
jdk:
  - oraclejdk8
install: true

addons:
  sonarcloud:
    organization: "power_flows"
    token:
      secure: "UDhBRDw4vfUWH4kf3zhcYtDkB0J7CkZ16rqq9aNXML3E0GaQLoP4w+milx7Q0yC11h4KA6O20YQ2Fd82IQzayr5b9o/GgK6462a72ECMDvA/la2w9e0nmBeyz3vxvPEIhlmN6O2LQ6Fhzl8jIXkyhhEsaN1lsOGQfbvuH+eA6urXmqi7RFXis5k7Ie2iea/Ue4mzAfcOW+X+ReGFWEdEMyoutkJLmVR7r8ccOnp1Z1hTZX/A+IRfXCw4JebryUQ+YEGn1zUl/KCy3XZGCVW1S2W4Vg/7+bbPEXv6SHwgYwKsMfOCnFyLvt/bGjfIOK/eZb8vJj1jBL/tjBHu/XF/aG8xwP3G4XF79y+yHRhMu7rNYjiOv2dLfC4Fzxw4VvNgHKHoyjwtjGNUraxZoFHacPAgz9HJ1du63/LtJ7tx/7e5tBi/GZvNV9EL7KLXuRHn9fUQU2KiEeINXqw1MUmDTjJCxRs6PmD2Ui2OKniqcoV1nGMDPOntZkx3JkNYXO5djnutK0r8uJ0eSn+4brRBz+Kk6DMVVped4w5eo4aXLxskZQu11+Q7MYHPCzOyYM6bmHtqjvoEZNo/rCqmeSxzllK+1VEXClGzwrJ+tvl7xC6MFUG7iF6ef37Y3XzoGoMagH5hOdTkzHOQrhFzVpXf/CXahodn2Uo3zOXNMZimZlA="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar